name: rmp2rl
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.6
  - numpy==1.19.0
  - pytorch==1.4.0
  - torchvision
  - pip
  - pip:
    - catkin_pkg
    - scipy==1.4.1
    - tqdm==4.32.1
    - matplotlib==3.2.2
    - tensorflow-cpu==2.3.1
    - ray[rllib]==1.0.0
    - ray[debug]==1.0.0
    - tensorflow-probability==0.11.1
    - urdf-parser-py
    - torchviz
    - natsort
    - pybullet
    - pyyaml